# Generated by Django 4.1.3 on 2022-12-08 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_category_comments_listings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bids',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='group',
            new_name='grouping',
        ),
        migrations.RenameField(
            model_name='listings',
            old_name='active',
            new_name='activelisting',
        ),
        migrations.AlterField(
            model_name='listings',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
