# Generated by Django 4.1.3 on 2022-12-11 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_listings_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='picture',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='startingbid',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='currentbid',
        ),
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='listingsWatchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
