# Generated by Django 4.1.3 on 2022-12-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_picture_listing_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='grouping',
            new_name='category_Name',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='image',
            new_name='imageUrl',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='activelisting',
            new_name='isActive',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='creator',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='date',
        ),
    ]
